language: go

go:
  - 1.11.x
  - 1.12.x

script:
  # build test for supported platforms
  - GO111MODULE=on make all
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod